# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - ./gradlew build
      - cp rustore-billing/RustoreBilling.gdap rustore-billing/build/outputs/aar/RustoreBilling.gdap

  example:
    deps: [build]
    cmds:
      - cp rustore-billing/build/outputs/aar/rustore-billing-debug.aar ./example/android/plugins/rustore-billing-release.aar
      - cp rustore-billing/build/outputs/aar/RustoreBilling.gdap ./example/android/plugins/RustoreBilling.gdap
