# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - ./gradlew build

  example:
    deps: [build]
    cmds:
      - cp rustore-billing/build/outputs/aar/rustore-billing-debug.aar ./example/android/plugins/rustore-billing.aar
      - cp rustore-billing/RustoreBilling.gdap ./example/android/plugins/RustoreBilling.gdap

  qa:
    deps: [build]
    cmds:
      - cp rustore-billing/build/outputs/aar/rustore-billing-debug.aar ./example/android/plugins/rustore-billing.aar
      - cp rustore-billing/RustoreBillingQA.gdap ./example/android/plugins/RustoreBilling.gdap

  release:
    deps: [build]
    cmds:
      - rm -rf ./release
      - mkdir -p ./release
      - cp rustore-billing/build/outputs/aar/rustore-billing-release.aar ./release/rustore-billing.aar
      - cp rustore-billing/RustoreBilling.gdap ./release/RustoreBilling.gdap
      - zip release.zip ./release/*